In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor

In [2]:
bike_arrivals = pd.read_csv("final_arrivals_data.csv",header=0,index_col=0)
bike_arrivals

C:\Users\katio\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


Timestamp   id  arrivals  day_of_week  day_of_year  \
0        2019-04-01 05:50:00   25         1            0           91   
1        2019-04-01 05:55:00   83         1            0           91   
2        2019-04-01 06:10:00   64         1            0           91   
3        2019-04-01 06:15:00  114         1            0           91   
4        2019-04-01 06:30:00   30         1            0           91   
...                      ...  ...       ...          ...          ...   
2652353  2019-11-03 15:50:00  260         1            6          307   
2652354  2019-11-03 16:55:00  731         1            6          307   
2652355  2019-11-04 06:55:00  551         1            0          308   
2652356  2019-11-04 10:30:00  138         2            0          308   
2652357  2019-11-04 11:20:00  525         1            0          308   

         Cloud amount (1/8)  Relative humidity (%)  \
0                       0.0                   71.0   
1                       0.0                   71.0   
2                       0.0                   67.0   
3                       0.0                   67.0   
4                       0.0                   65.0   
...                     ...                    ...   
2652353                 3.0                   96.0   
2652354                 0.0                   98.0   
2652355                 7.0                   84.0   
2652356                 7.0                   77.0   
2652357                 0.0                   76.0   

         Precipitation intensity (mm/h)  Air temperature (degC)  \
0                                   0.0                     1.4   
1                                   0.0                     1.4   
2                                   0.0                     2.0   
3                                   0.0                     2.0   
4                                   0.0                     2.3   
...                                 ...                     ...   
2652353                             0.0                     1.9   
2652354                             0.0                     1.0   
2652355                             0.0                    -1.1   
2652356                             0.0                     0.0   
2652357                             0.0                     0.1   

         Wind speed (m/s)  time  
0                     5.3    71  
1                     5.3    72  
2                     4.4    75  
3                     4.4    76  
4                     4.5    79  
...                   ...   ...  
2652353               2.3   191  
2652354               2.4   204  
2652355               5.0    84  
2652356               5.2   127  
2652357               5.5   137  

[2652358 rows x 11 columns]

In [3]:
X = bike_arrivals[['time','day_of_week','day_of_year','Cloud amount (1/8)','Relative humidity (%)','Precipitation intensity (mm/h)','Air temperature (degC)','Wind speed (m/s)']].values.reshape(-1, 8)
y = bike_arrivals['arrivals'].values.reshape(-1, 1).ravel()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

model = MLPRegressor(random_state = 1)
model.fit(X_train,y_train)

print(model.predict(X_test))
print(y_test)
model.score(X_test,y_test)

[1.41023189 1.55517113 1.45193888 ... 1.40469114 1.41536991 1.10421674]
[1 2 7 ... 1 2 1]


0.022662914818290414

In [5]:
sum(abs(a-b) <=1 for a,b in zip(model.predict(X_test),list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.9097522047255789

In [6]:
sum(abs(a-b) <=2 for a,b in zip(model.predict(X_test),list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.966840287496901

In [10]:
round_predict = [ round(elem) for elem in model.predict(X_test) ]
round_predict

[1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 2,


In [11]:
sum(abs(a-b) <=1 for a,b in zip(round_predict,list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.9270952462014969

We have a very good score but we can see that the predicted values are only 1 and 2 (when rounded)
I wanted to look at the data where the number of arrivals is > 2 and compare it with the predicted values

In [26]:
# Real values
df_y_test = pd.DataFrame(y_test)
df_y_test.loc[df_y_test[0] > 2]


(875279, 1)


0
2       7
21      3
23      3
30      3
40      4
...    ..
875226  3
875234  3
875236  3
875249  3
875269  3

[78912 rows x 1 columns]

In [28]:
# Predicted values
df_y_predict = pd.DataFrame(round_predict)
df_y_predict.loc[df_y_test.loc[df_y_test[0] > 2].index]

0
2       1
21      1
23      2
30      1
40      1
...    ..
875226  1
875234  1
875236  1
875249  1
875269  1

[78912 rows x 1 columns]

In [49]:
# I looked at the pourcentage of values > 2 in the entire dataset
# We can see that it's about 9% and we have about 7% of bad predictions so we can conclude that the values that are not well predicted are the values that are > 2
print(df_y_test.loc[df_y_test[0] > 2].shape[0]/df_y_test.shape[0])

0.09015639584635299


However, since we have data for every five minutes, I think that it's normal.<br>
Usually, it's normal to have 1-2-3 bikes that are arriving at a moment. It's very unusual to have 5-7 bikes at once.<br>
So it's very complicated to predict these.

In [60]:
# I will now look at the predictions score in the data where the rsum(abs(a-b) <=1 for a,b in zip(df_y_test.loc[df_y_test[0] > 2][0].tolist(),df_y_predict.loc[df_y_test.loc[df_y_test[0] > 2].index][0].tolist()))/len(df_y_test.loc[df_y_test[0] > 2][0].tolist())eal number of arrivals is > 2
sum(abs(a-b) <=1 for a,b in zip(df_y_test.loc[df_y_test[0] > 2][0].tolist(),df_y_predict.loc[df_y_test.loc[df_y_test[0] > 2].index][0].tolist()))/len(df_y_test.loc[df_y_test[0] > 2][0].tolist())

0.19135239253852393

In [61]:
# So in the data where the number of arrivals is > 2, we have 80% that were badly predicted
1 - sum(abs(a-b) <=1 for a,b in zip(df_y_test.loc[df_y_test[0] > 2][0].tolist(),df_y_predict.loc[df_y_test.loc[df_y_test[0] > 2].index][0].tolist()))/len(df_y_test.loc[df_y_test[0] > 2][0].tolist())

0.8086476074614761

In [68]:
# In the entire data set, it corresponds to about 7% of bad predictions
(1 - sum(abs(a-b) <=1 for a,b in zip(df_y_test.loc[df_y_test[0] > 2][0].tolist(),df_y_predict.loc[df_y_test.loc[df_y_test[0] > 2].index][0].tolist()))/len(df_y_test.loc[df_y_test[0] > 2][0].tolist())) * (df_y_test.loc[df_y_test[0] > 2].shape[0]/df_y_test.shape[0])

0.07290475379850311

In [69]:
# In the entire data set it conresponds to about 93% of good predictions and we can see that it corresponds exactly to the predictions score !
# It means that the badly predicted values are some values that are > 2
1 - (1 - sum(abs(a-b) <=1 for a,b in zip(df_y_test.loc[df_y_test[0] > 2][0].tolist(),df_y_predict.loc[df_y_test.loc[df_y_test[0] > 2].index][0].tolist()))/len(df_y_test.loc[df_y_test[0] > 2][0].tolist())) * (df_y_test.loc[df_y_test[0] > 2].shape[0]/df_y_test.shape[0])

0.9270952462014969

In [70]:
# I compare the two values to see if they are equal
1 - (1 - sum(abs(a-b) <=1 for a,b in zip(df_y_test.loc[df_y_test[0] > 2][0].tolist(),df_y_predict.loc[df_y_test.loc[df_y_test[0] > 2].index][0].tolist()))/len(df_y_test.loc[df_y_test[0] > 2][0].tolist())) * (df_y_test.loc[df_y_test[0] > 2].shape[0]/df_y_test.shape[0]) == sum(abs(a-b) <=1 for a,b in zip(round_predict,list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

True

_____

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor

bike_departures = pd.read_csv("final_departures_data.csv",header=0,index_col=0)
bike_departures 

C:\Users\katio\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


Timestamp   id  departures  day_of_week  day_of_year  \
0        2019-04-01 05:40:00   60           1            0           91   
1        2019-04-01 05:50:00   85           1            0           91   
2        2019-04-01 06:00:00   86           1            0           91   
3        2019-04-01 06:05:00   26           1            0           91   
4        2019-04-01 06:10:00   35           1            0           91   
...                      ...  ...         ...          ...          ...   
2597574  2019-10-31 23:50:00   82           2            3          304   
2597575  2019-10-31 23:50:00   95           1            3          304   
2597576  2019-10-31 23:50:00  161           1            3          304   
2597577  2019-10-31 23:55:00   22           1            3          304   
2597578  2019-10-31 23:55:00  260           1            3          304   

         Cloud amount (1/8)  Relative humidity (%)  \
0                       0.0                   74.0   
1                       0.0                   71.0   
2                       0.0                   68.0   
3                       0.0                   68.0   
4                       0.0                   67.0   
...                     ...                    ...   
2597574                 0.0                   94.0   
2597575                 0.0                   94.0   
2597576                 0.0                   94.0   
2597577                 0.0                   94.0   
2597578                 0.0                   94.0   

         Precipitation intensity (mm/h)  Air temperature (degC)  \
0                                   0.0                     1.1   
1                                   0.0                     1.4   
2                                   0.0                     1.7   
3                                   0.0                     1.7   
4                                   0.0                     2.0   
...                                 ...                     ...   
2597574                             0.0                     0.1   
2597575                             0.0                     0.1   
2597576                             0.0                     0.1   
2597577                             0.0                     0.1   
2597578                             0.0                     0.1   

         Wind speed (m/s)  time  
0                     4.8    69  
1                     5.3    71  
2                     5.0    73  
3                     5.0    74  
4                     4.4    75  
...                   ...   ...  
2597574               4.6   287  
2597575               4.6   287  
2597576               4.6   287  
2597577               4.6   288  
2597578               4.6   288  

[2597579 rows x 11 columns]

In [3]:
X = bike_departures [['time','day_of_week','day_of_year','Cloud amount (1/8)','Relative humidity (%)','Precipitation intensity (mm/h)','Air temperature (degC)','Wind speed (m/s)']].values.reshape(-1, 8)
y = bike_departures ['departures'].values.reshape(-1, 1).ravel()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

model = MLPRegressor(random_state = 1)
model.fit(X_train,y_train)

print(model.predict(X_test))
print(y_test)
model.score(X_test,y_test)

[1.57866192 1.34767019 1.6754775  ... 1.43955839 1.50982557 1.38115616]
[1 2 2 ... 1 1 1]


0.023159610841252065

In [4]:
sum(abs(a-b) <=1 for a,b in zip(model.predict(X_test),list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.9016964496116434

In [5]:
sum(abs(a-b) <=2 for a,b in zip(model.predict(X_test),list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.9624184264619075

In [6]:
round_predict = [ round(elem) for elem in model.predict(X_test) ]
round_predict

[2,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 2,


In [7]:
sum(abs(a-b) <=1 for a,b in zip(round_predict,list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.9380612737721097