In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor

In [2]:
bike_arrivals = pd.read_csv("final_arrivals_data.csv",header=0,index_col=0)

X = bike_arrivals[['id','time','day_of_week','day_of_year','Cloud amount (1/8)','Relative humidity (%)','Precipitation intensity (mm/h)','Air temperature (degC)','Wind speed (m/s)']].values.reshape(-1, 9)
y = bike_arrivals['arrivals'].values.reshape(-1, 1).ravel()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

model = MLPRegressor(random_state = 1)
model.fit(X_train,y_train)

print(model.predict(X_test))
print(y_test)

C:\Users\katio\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
C:\Users\katio\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:619: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


[0.72663675 1.26932464 1.13389412 ... 0.82172003 0.99029982 0.69115351]
[1 2 7 ... 1 2 1]


In [ ]:
round_predict = [ round(elem) for elem in model.predict(X_test) ]

In [ ]:
sum(abs(a-b) <=1 for a,b in zip(round_predict,list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.9398077641529158

In [ ]:
sum(abs(a-b) ==0 for a,b in zip(round_predict,list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.6152141202976422

In [ ]:
bike_departures = pd.read_csv("final_departures_data.csv",header=0,index_col=0)

X = bike_departures [['id','time','day_of_week','day_of_year','Cloud amount (1/8)','Relative humidity (%)','Precipitation intensity (mm/h)','Air temperature (degC)','Wind speed (m/s)']].values.reshape(-1, 9)
y = bike_departures ['departures'].values.reshape(-1, 1).ravel()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

model = MLPRegressor(random_state = 1)
model.fit(X_train,y_train)

print(model.predict(X_test))
print(y_test)

round_predict = [ round(elem) for elem in model.predict(X_test) ]

C:\Users\katio\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[1.59596032 1.71208212 1.9976011  ... 1.3849168  1.81999374 1.45049989]
[1 2 2 ... 1 1 1]


In [ ]:
sum(abs(a-b) <=1 for a,b in zip(round_predict,list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.9333377663607878

In [ ]:
sum(abs(a-b) ==0 for a,b in zip(round_predict,list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.5928660922396355

____
Second test with more features

In [11]:
import numpy as np
bike_arrivals['6hrs_ago'] = np.nan
bike_arrivals

Timestamp   id  arrivals  day_of_week  day_of_year  \
0        2019-04-01 05:50:00   25         1            0           91   
1        2019-04-01 05:55:00   83         1            0           91   
2        2019-04-01 06:10:00   64         1            0           91   
3        2019-04-01 06:15:00  114         1            0           91   
4        2019-04-01 06:30:00   30         1            0           91   
...                      ...  ...       ...          ...          ...   
2652353  2019-11-03 15:50:00  260         1            6          307   
2652354  2019-11-03 16:55:00  731         1            6          307   
2652355  2019-11-04 06:55:00  551         1            0          308   
2652356  2019-11-04 10:30:00  138         2            0          308   
2652357  2019-11-04 11:20:00  525         1            0          308   

         Cloud amount (1/8)  Relative humidity (%)  \
0                       0.0                   71.0   
1                       0.0                   71.0   
2                       0.0                   67.0   
3                       0.0                   67.0   
4                       0.0                   65.0   
...                     ...                    ...   
2652353                 3.0                   96.0   
2652354                 0.0                   98.0   
2652355                 7.0                   84.0   
2652356                 7.0                   77.0   
2652357                 0.0                   76.0   

         Precipitation intensity (mm/h)  Air temperature (degC)  \
0                                   0.0                     1.4   
1                                   0.0                     1.4   
2                                   0.0                     2.0   
3                                   0.0                     2.0   
4                                   0.0                     2.3   
...                                 ...                     ...   
2652353                             0.0                     1.9   
2652354                             0.0                     1.0   
2652355                             0.0                    -1.1   
2652356                             0.0                     0.0   
2652357                             0.0                     0.1   

         Wind speed (m/s)  time  6hrs_ago  
0                     5.3    71       NaN  
1                     5.3    72       NaN  
2                     4.4    75       NaN  
3                     4.4    76       NaN  
4                     4.5    79       NaN  
...                   ...   ...       ...  
2652353               2.3   191       NaN  
2652354               2.4   204       NaN  
2652355               5.0    84       NaN  
2652356               5.2   127       NaN  
2652357               5.5   137       NaN  

[2652358 rows x 12 columns]

In [10]:
bikes = pd.read_csv('station_with_bikes.csv',header=0,index_col=0)
bikes

C:\Users\katio\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


id  bikesAvailable  spacesAvailable            Timestamp
0         591               4               20  2019-04-02 13:55:00
3         110               1               19  2019-04-02 13:55:00
5         111               1               19  2019-04-02 13:55:00
7         595               3               13  2019-04-02 13:55:00
8         112              10               12  2019-04-02 13:55:00
...       ...             ...              ...                  ...
25965948  511               4                7  2019-11-11 11:45:00
25965955  516               1                9  2019-11-11 11:45:00
25965957  514               7                4  2019-11-11 11:45:00
25965968  521               5                7  2019-11-11 11:45:00
25965971  526               4                8  2019-11-11 11:45:00

[22283214 rows x 4 columns]