In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor

In [16]:
bike_arrivals = pd.read_json("clean_arivals.json",orient="columns")
bike_arrivals

datetime   id  arrivals  day_of_week  day_of_year  time
0       2019-04-01 05:50:00   25         1            0           91    71
1       2019-04-01 05:55:00   83         1            0           91    72
2       2019-04-01 06:10:00   64         1            0           91    75
3       2019-04-01 06:15:00  114         1            0           91    76
4       2019-04-01 06:30:00   30         1            0           91    79
...                     ...  ...       ...          ...          ...   ...
2652353 2019-11-03 15:50:00  260         1            6          307   191
2652354 2019-11-03 16:55:00  731         1            6          307   204
2652355 2019-11-04 06:55:00  551         1            0          308    84
2652356 2019-11-04 10:30:00  138         2            0          308   127
2652357 2019-11-04 11:20:00  525         1            0          308   137

[2652358 rows x 6 columns]

In [17]:
X = bike_arrivals[['time','day_of_week','day_of_year']].values.reshape(-1, 3)
y = bike_arrivals['arrivals'].values.reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

model = MLPRegressor(random_state = 1)
model.fit(X_train,y_train)

print(model.predict(X_test))
print(y_test)
model.score(X_test,y_test)

C:\Users\katio\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


[1.42673069 1.44895684 1.44895684 ... 1.37235577 1.43460316 1.44895684]
[[1]
 [2]
 [7]
 ...
 [1]
 [2]
 [1]]


0.0072498239386118435

In [20]:
sum(abs(a-b) <=2 for a,b in zip(model.predict(X_test),list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.9668208651184366

In [21]:
sum(abs(a-b) <=3 for a,b in zip(model.predict(X_test),list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.9866111262808773

In [22]:
sum(abs(a-b) <=4 for a,b in zip(model.predict(X_test),list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.9941789989249142

In [23]:
sum(abs(a-b) <=5 for a,b in zip(model.predict(X_test),list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.997262587129361

In [2]:
bike_departures = pd.read_json("clean_departures.json",orient="columns")
bike_departures

datetime   id  departures  day_of_week  day_of_year  time
0       2019-04-01 05:40:00   60           1            0           91    69
1       2019-04-01 05:50:00   85           1            0           91    71
2       2019-04-01 06:00:00   86           1            0           91    73
3       2019-04-01 06:05:00   26           1            0           91    74
4       2019-04-01 06:10:00   35           1            0           91    75
...                     ...  ...         ...          ...          ...   ...
2597574 2019-10-31 23:50:00   82           2            3          304   287
2597575 2019-10-31 23:50:00   95           1            3          304   287
2597576 2019-10-31 23:50:00  161           1            3          304   287
2597577 2019-10-31 23:55:00   22           1            3          304   288
2597578 2019-10-31 23:55:00  260           1            3          304   288

[2597579 rows x 6 columns]

In [4]:
X = bike_departures[['time','day_of_week','day_of_year']].values.reshape(-1, 3)
y = bike_departures['departures'].values.reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

model = MLPRegressor(random_state = 1)
model.fit(X_train,y_train)

print(model.predict(X_test))
print(y_test)
model.score(X_test,y_test)

C:\Users\katio\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


[1.54959858 1.35757978 1.54959858 ... 1.49311292 1.47819039 1.44050315]
[[1]
 [2]
 [2]
 ...
 [1]
 [1]
 [1]]


0.009569876936783572

In [5]:
sum(abs(a-b) <=2 for a,b in zip(model.predict(X_test),list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.9624207596342519