In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [5]:
data = pd.read_csv("station_with_bikes.csv",header=0,index_col=0)

C:\Users\katio\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [6]:
data = data.loc[data['id']==204]
data.time = pd.to_datetime(data.time)
data.date = pd.to_datetime(data.date)
data

id  bikesAvailable  spacesAvailable       state       date  \
8034853   204               4               22  Station on 2019-06-26   
8035299   204               4               22  Station on 2019-06-26   
8035745   204               4               22  Station on 2019-06-26   
8036191   204               4               22  Station on 2019-06-26   
8036637   204               4               22  Station on 2019-06-26   
...       ...             ...              ...         ...        ...   
24541409  204               1               24  Station on 2019-10-31   
24541873  204               2               23  Station on 2019-10-31   
24542337  204               1               24  Station on 2019-10-31   
24544657  204               1               24  Station on 2019-10-31   
24545121  204               1               24  Station on 2019-10-31   

                        time  
8034853  2021-10-12 11:35:02  
8035299  2021-10-12 11:40:03  
8035745  2021-10-12 11:45:03  
8036191  2021-10-12 11:50:03  
8036637  2021-10-12 11:55:03  
...                      ...  
24541409 2021-10-12 17:10:03  
24541873 2021-10-12 17:15:02  
24542337 2021-10-12 17:20:02  
24544657 2021-10-12 17:45:03  
24545121 2021-10-12 17:50:02  

[28521 rows x 6 columns]

In [7]:
data['day_of_year'] = data['date'].dt.dayofyear
data

id  bikesAvailable  spacesAvailable       state       date  \
8034853   204               4               22  Station on 2019-06-26   
8035299   204               4               22  Station on 2019-06-26   
8035745   204               4               22  Station on 2019-06-26   
8036191   204               4               22  Station on 2019-06-26   
8036637   204               4               22  Station on 2019-06-26   
...       ...             ...              ...         ...        ...   
24541409  204               1               24  Station on 2019-10-31   
24541873  204               2               23  Station on 2019-10-31   
24542337  204               1               24  Station on 2019-10-31   
24544657  204               1               24  Station on 2019-10-31   
24545121  204               1               24  Station on 2019-10-31   

                        time  day_of_year  
8034853  2021-10-12 11:35:02          177  
8035299  2021-10-12 11:40:03          177  
8035745  2021-10-12 11:45:03          177  
8036191  2021-10-12 11:50:03          177  
8036637  2021-10-12 11:55:03          177  
...                      ...          ...  
24541409 2021-10-12 17:10:03          304  
24541873 2021-10-12 17:15:02          304  
24542337 2021-10-12 17:20:02          304  
24544657 2021-10-12 17:45:03          304  
24545121 2021-10-12 17:50:02          304  

[28521 rows x 7 columns]

In [8]:
data['time'] = data['time'].dt.strftime('%H:%M')
data

id  bikesAvailable  spacesAvailable       state       date   time  \
8034853   204               4               22  Station on 2019-06-26  11:35   
8035299   204               4               22  Station on 2019-06-26  11:40   
8035745   204               4               22  Station on 2019-06-26  11:45   
8036191   204               4               22  Station on 2019-06-26  11:50   
8036637   204               4               22  Station on 2019-06-26  11:55   
...       ...             ...              ...         ...        ...    ...   
24541409  204               1               24  Station on 2019-10-31  17:10   
24541873  204               2               23  Station on 2019-10-31  17:15   
24542337  204               1               24  Station on 2019-10-31  17:20   
24544657  204               1               24  Station on 2019-10-31  17:45   
24545121  204               1               24  Station on 2019-10-31  17:50   

          day_of_year  
8034853           177  
8035299           177  
8035745           177  
8036191           177  
8036637           177  
...               ...  
24541409          304  
24541873          304  
24542337          304  
24544657          304  
24545121          304  

[28521 rows x 7 columns]

In [9]:
time_convert = pd.DataFrame(pd.date_range(start="00:00:00",end="23:55:00",freq ='5T').strftime('%H:%M'))
time_convert.rename(columns = {0:'time'}, inplace = True)
time_convert['to_int'] = pd.RangeIndex(start=1,stop=time_convert.shape[0]+1)
time_convert = time_convert.set_index('time')
time_convert

to_int
time         
00:00       1
00:05       2
00:10       3
00:15       4
00:20       5
...       ...
23:35     284
23:40     285
23:45     286
23:50     287
23:55     288

[288 rows x 1 columns]

In [10]:
print(data)
data2 = data.join(time_convert,on="time")
data2

           id  bikesAvailable  spacesAvailable       state       date   time  \
8034853   204               4               22  Station on 2019-06-26  11:35   
8035299   204               4               22  Station on 2019-06-26  11:40   
8035745   204               4               22  Station on 2019-06-26  11:45   
8036191   204               4               22  Station on 2019-06-26  11:50   
8036637   204               4               22  Station on 2019-06-26  11:55   
...       ...             ...              ...         ...        ...    ...   
24541409  204               1               24  Station on 2019-10-31  17:10   
24541873  204               2               23  Station on 2019-10-31  17:15   
24542337  204               1               24  Station on 2019-10-31  17:20   
24544657  204               1               24  Station on 2019-10-31  17:45   
24545121  204               1               24  Station on 2019-10-31  17:50   

          day_of_year  
8034853        

id  bikesAvailable  spacesAvailable       state       date   time  \
8034853   204               4               22  Station on 2019-06-26  11:35   
8035299   204               4               22  Station on 2019-06-26  11:40   
8035745   204               4               22  Station on 2019-06-26  11:45   
8036191   204               4               22  Station on 2019-06-26  11:50   
8036637   204               4               22  Station on 2019-06-26  11:55   
...       ...             ...              ...         ...        ...    ...   
24541409  204               1               24  Station on 2019-10-31  17:10   
24541873  204               2               23  Station on 2019-10-31  17:15   
24542337  204               1               24  Station on 2019-10-31  17:20   
24544657  204               1               24  Station on 2019-10-31  17:45   
24545121  204               1               24  Station on 2019-10-31  17:50   

          day_of_year  to_int  
8034853           177   140.0  
8035299           177   141.0  
8035745           177   142.0  
8036191           177   143.0  
8036637           177   144.0  
...               ...     ...  
24541409          304   207.0  
24541873          304   208.0  
24542337          304   209.0  
24544657          304   214.0  
24545121          304   215.0  

[28521 rows x 8 columns]

In [11]:
#problem with this line
data2.loc[data2['to_int'].isnull()==True]
#I remove it for now
data2.drop(8345269,inplace=True)
#no more problem
data2.loc[data2['to_int'].isnull()==True]


Empty DataFrame
Columns: [id, bikesAvailable, spacesAvailable, state, date, time, day_of_year, to_int]
Index: []

In [12]:
data2['day_week'] = data['date'].dt.dayofweek
data2

id  bikesAvailable  spacesAvailable       state       date   time  \
8034853   204               4               22  Station on 2019-06-26  11:35   
8035299   204               4               22  Station on 2019-06-26  11:40   
8035745   204               4               22  Station on 2019-06-26  11:45   
8036191   204               4               22  Station on 2019-06-26  11:50   
8036637   204               4               22  Station on 2019-06-26  11:55   
...       ...             ...              ...         ...        ...    ...   
24541409  204               1               24  Station on 2019-10-31  17:10   
24541873  204               2               23  Station on 2019-10-31  17:15   
24542337  204               1               24  Station on 2019-10-31  17:20   
24544657  204               1               24  Station on 2019-10-31  17:45   
24545121  204               1               24  Station on 2019-10-31  17:50   

          day_of_year  to_int  day_week  
8034853           177   140.0         2  
8035299           177   141.0         2  
8035745           177   142.0         2  
8036191           177   143.0         2  
8036637           177   144.0         2  
...               ...     ...       ...  
24541409          304   207.0         3  
24541873          304   208.0         3  
24542337          304   209.0         3  
24544657          304   214.0         3  
24545121          304   215.0         3  

[28520 rows x 9 columns]

In [18]:
from sklearn.linear_model import LinearRegression

X = data2['day_of_year'].values.reshape(-1, 1)
y = data2['bikesAvailable'].values.reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

model = LinearRegression()
model.fit(X_train,y_train)

print(model.predict(X_test))
print(y_test)
model.score(X_test,y_test)

[[6.10062349]
 [6.74922787]
 [4.70612408]
 ...
 [4.51154277]
 [5.03042627]
 [8.43559926]]
[[6]
 [4]
 [1]
 ...
 [3]
 [7]
 [9]]


0.027315099270218246

In [19]:
sum(abs(a-b) <=2 for a,b in zip(model.predict(X_test),list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

array([0.20112622])

In [20]:
X = data2[['to_int','day_of_year']].values.reshape(-1, 2)
y = data2['bikesAvailable'].values.reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

model = LinearRegression()
model.fit(X_train,y_train)

print(model.predict(X_test))
print(y_test)
model.score(X_test,y_test)

[[5.6902941 ]
 [5.78939478]
 [3.81748001]
 ...
 [4.22597399]
 [4.91495774]
 [8.19795399]]
[[6]
 [4]
 [1]
 ...
 [3]
 [7]
 [9]]


0.04236488971020147

In [21]:
sum(abs(a-b) <=2 for a,b in zip(model.predict(X_test),list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

array([0.21982575])

In [24]:
from sklearn.neural_network import MLPRegressor

X = data2[['to_int','day_week','day_of_year']].values.reshape(-1, 3)
y = data2['bikesAvailable'].values.reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

model = MLPRegressor(random_state = 1)
model.fit(X_train,y_train)

print(model.predict(X_test))
print(y_test)
model.score(X_test,y_test)

C:\Users\katio\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


[ 4.15948717  4.62288888  3.00437027 ...  3.4380982   4.21955934
 13.90610359]
[[6]
 [4]
 [1]
 ...
 [3]
 [7]
 [9]]


0.30213801615325986

In [25]:
sum(abs(a-b) <=2 for a,b in zip(model.predict(X_test),list(y_test.reshape(1, -1)[0])))/len(list(y_test.reshape(1, -1)[0]))

0.29345516362090945